syntax enable
colorscheme monokai
set guifont=*
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab
set mouse=a
autocmd InsertEnter * set cul
autocmd InsertLeave * set nocul
"let g:molokai_original = 1
"let g:rehash256 = 1
